name: app_previsao_do_tempo
description: "App de Previsão do Tempo com Geolocalização."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.0
  http: ^1.3.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  weather_icons: ^3.0.0
  country_codes: ^3.3.0
  fl_chart: ^0.71.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true